[package]
name = "fg"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
itertools = "0.12.0"

[dev-dependencies]
insta = "1.34.0"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
